"""outro modelo user

Revision ID: 7b90355e3818
Revises: 56923d7e2ce8
Create Date: 2024-04-28 02:14:16.431797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b90355e3818'
down_revision = '56923d7e2ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=40), nullable=True))
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
